### ISSUE TITLE
Workflow auto-download (specified in config.yaml)

### ISSUE THREAD

**Issue by Avsecz** [snakemake-workflows/docs#7]
snakemake workflows is a great idea! Thanks for putting it together.

## API Suggestion

What do you think about having a command line tool for running any snakemake workflow with the following user API
- `sworkflow config.yaml [other snakemake flags]`

`config.yaml` would be the standard `config.yaml` with an additional `workflow` entry specifying which workflow to use (as a string):
```yaml
workflow: https://github.com/snakemake-workflows/single-cell-rna-seq/tree/a1be3b6b389b009d91bb1d7f75abc1b5a23cd19d

# The usual config.yaml ----------------------------------
# path to sheet describing each cell.
cells: cells.tsv

# specify count table (rows: genes/transcripts/spikes, cols: cells)
counts: counts.tsv
...
```

This functionality is conceptually similar to [snakemake rule wrappers](http://snakemake.readthedocs.io/en/latest/snakefiles/modularization.html#wrappers), where you refer to a command with a single string.

## Implementation
`sworkflow` command would do the following:
1. Git checkout the workflow source code to a common location (`~/.snakemake/workflows/<myworkflow>`?)
2. Run the snakemake command: `snakemake --snakefile ~/.snakemake/workflows/<myworkflow>/Snakefile [other snakemake flags]`

## Motivation
This command would come handy in case you want to apply a single workflow multiple times (say you are analyzing different but related datasets). In the current case, you'd need to checkout the source-code to each directory.
